[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "nginx.conf.tmpl"

# The location to place the rendered configuration file
dest = "/etc/nginx/nginx.conf"

# File ownership and mode information
owner = "root"
mode = "0644"
